### ISSUE TITLE
Support for local files

### ISSUE THREAD

**Issue by itsdoublearon** [OpenBMB/ChatDev#157] opened 2023-10-10 00:25 UTC
I would like the ability to have the support for local files. For example is a have an existing Python script I would like the ChatDev to use as a reference or guide, I would like the ability to have ChatDev go to the specified file and read it.

**Comment by delconis** [comment] 2023-10-10 16:22
This is a duplicate of one of the following #147 #80 #94

**Closed** 2023-10-16 11:19 UTC
